spring.jpa.hibernate.ddl-auto: create-drop
spring.jpa.hibernate.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.database: H2
spring.jpa.show-sql: true
spring.h2.console.enabled: true

spring.datasource.url: jdbc:h2:tcp://localhost/~/dukemarket

#jdbc:h2:tcp://localhost/~/dukemarket

#datasource.mine.jdbcUrl: jdbc:h2:mem:mydb
#datasource.mine.user: sa
#datasource.mine.poolSize: 30

#logging.level.org.springframework: DEBUG
# implement chunked file upload
multipart.maxFileSize: 100MB
multipart.maxRequestSize: 100MB
bundles.dir: /tmp/dukemarket/bundles
server.port: 8088